@import org.svenehrke.demo.web.p02simplevcdemos.page02withcomponent.PageWithComponentCode

<div class="codeblock">
    <strong>PageWithComponent.jte</strong>
    <pre><code>${PageWithComponentCode.PAGE_JTE}</code></pre>
    <hr>
    <strong>HelloWorld.jte</strong>
    <pre><code>${PageWithComponentCode.HELLO_WORLD_JTE}</code></pre>
    <hr>
    <strong>PageWithComponent.java</strong>
    <pre><code>${PageWithComponentCode.PAGE_JAVA}</code></pre>
</div>

