@import jte.plainjte.Page05NestedCode

<div class="codearea">
  <div class="codeareacell">
    <strong>page04passcontent.jte</strong>
    <pre><code>${Page05NestedCode.PAGE_JTE}</code></pre>
  </div>
  <div class="codeareacell">
    <strong>PlainJTEController.java</strong>
    <pre><code>${Page05NestedCode.PAGE_JAVA}</code></pre>
  </div>
  <div class="codeareacell">
    <strong>helloworldcontent.jte</strong>
    <pre><code>${Page05NestedCode.HELLO_WORLD_JTE}</code></pre>
  </div>
</div>
