@import jte.plainjte.Page04PassContentCode

<div class="codeblock">
    <strong>page04passcontent.jte</strong>
    <pre><code>${Page04PassContentCode.PAGE_JTE}</code></pre>
    <hr>
    <strong>helloworldcontent.jte</strong>
    <pre><code>${Page04PassContentCode.HELLO_WORLD_JTE}</code></pre>
    <hr>
    <strong>PlainJTEController.java</strong>
    <pre><code>${Page04PassContentCode.PAGE_JAVA}</code></pre>
</div>
