@import jte.plainjte.Page03InclParamsCode

<div class="codeblock">
    <strong>page03inclparams.jte</strong>
    <pre><code>${Page03InclParamsCode.PAGE_JTE}</code></pre>
    <hr>
    <strong>helloworldparams.jte</strong>
    <pre><code>${Page03InclParamsCode.HELLO_WORLD_JTE}</code></pre>
    <hr>
    <strong>PlainJTEController.java</strong>
    <pre><code>${Page03InclParamsCode.PAGE_JAVA}</code></pre>
</div>
