<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/simplepage.css"/>
</head>
<body class="page">
<div>
<!-- docs:start page -->
<h1>Page with Component</h1>

<!-- Include Component: -->
@template.jte.components.helloworld()
<!-- docs:end page -->

<hr>
<a href="http://localhost:4321/demos/s01/#2-basic-page-using-a-jte-component">Docs</a>

</div>
</body>
</html>

