@param String url
@param gg.jte.Content title
@param gg.jte.Content content

<div class="cell is-flex is-justify-content-start is-align-items-center">
    <div class="card" style="width: 50%; height: 100%">
        <a href="${url}" target="_blank">
            <header class="card-header">
                <p class="card-header-title">${title}</p>
            </header>
            <div class="card-content">
                ${content}
            </div>
        </a>
    </div>
</div>
