@import org.svenehrke.demo.web.p03pages.p03custompagewithparam.CustomPageWithParamCode

<div class="fixed-grid">
    <div class="grid">

<%-- -------------------------------- CustomPageWithParam ------------------------------ --%>
<div>
<strong>CustomPageWithParam.jte</strong>
<pre><code>${CustomPageWithParamCode.JTE}</code></pre>
</div>

<div>
<strong>CustomPageWithParam.java</strong>
<pre><code>${CustomPageWithParamCode.JAVA}</code></pre>
</div>

    </div>
</div>

